Repository WhileNotSuccess/project_OIC-Backend_NestJS-deployment-repo, pull requests merged in 2025-04, with the labels that each got.

#5 Clean test/staff
  api/.prettierrc
  api/eslint.config.mjs
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/staff/application/dto/create-staff.dto.ts
  api/src/staff/application/dto/update-staff.dto.ts
  api/src/staff/application/service/staff.service.spec.ts
  api/src/staff/application/service/staff.service.ts
  api/src/staff/domain/entities/staff.entity.ts
  api/src/staff/domain/repository/staff.repository.ts
  api/src/staff/infra/entities/staff.entity.ts
  api/src/staff/infra/mappers/staff.mapper.ts
  api/src/staff/infra/repository/typeorm-staff.repository.spec.ts
  api/src/staff/infra/repository/typeorm-staff.repository.ts
  api/src/staff/interface/staff.controller.spec.ts
  api/src/staff/interface/staff.controller.ts
  api/src/staff/staff.module.ts
  api/test/app.e2e-spec.ts
  api/test/jest-e2e.json
  api/test/staff.e2e-spec.ts
  api/test/types/staff-response.ts
  api/tsconfig.json
  docker-compose.yml
Labels: enhancement

#9 🐛 fix : .env DB_HOST
  .env
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/etc.template.md
  .github/ISSUE_TEMPLATE/feature_temlplate.md
  .github/ISSUE_TEMPLATE/refactoring_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐛 BugFix

#18 파일 업로드 수정
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/common/request-with-cookies.ts
  api/src/common/utils/to-language-enum.ts
  api/src/main.ts
  api/src/media/domain/image-metadata.ts
  api/src/media/domain/media.service.ts
  api/src/media/domain/upload-attachment.ts
  api/src/media/infra/local-media.service.spec.ts
  api/src/media/infra/local-media.service.ts
  api/src/post/application/dto/create-post.dto.ts
  api/src/post/application/dto/update-post.dto.ts
  api/src/post/application/service/post.service.ts
  api/src/post/domain/entities/attachment.entity.ts
  api/src/post/domain/entities/post-image.entity.ts
  api/src/post/domain/entities/post.entity.ts
  api/src/post/domain/repository/post.repository.ts
  api/src/post/domain/types/language.ts
  api/src/post/domain/types/news.ts
  api/src/post/domain/types/searchTarget.ts
  api/src/post/infra/entities/attachment-orm.entity.ts
  api/src/post/infra/entities/post-image-orm-entity.ts
  api/src/post/infra/entities/post-orm.entity.ts
  api/src/post/infra/mapper/to-domain.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/interface/post.controller.ts
  api/src/post/post.module.ts
Labels: ⭐ Feature

#19 Feature/carousel
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/carousel/application/dto/create-carousel.dto.ts
  api/src/carousel/application/dto/update-carousel.dto.ts
  api/src/carousel/application/services/carousel.service.spec.ts
  api/src/carousel/application/services/carousel.service.ts
  api/src/carousel/carousel.model.ts
  api/src/carousel/domain/entities/carousel-return.entiry.ts
  api/src/carousel/domain/entities/carousel.entity.ts
  api/src/carousel/domain/repository/carousel.repository.ts
  api/src/carousel/infra/entites/carousel.entity.ts
  api/src/carousel/infra/mappers/carousel.mapper.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.spec.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.ts
  api/src/carousel/interface/controllers/carousel.controller.spec.ts
  api/src/carousel/interface/controllers/carousel.controller.ts
  api/src/main.ts
  api/src/pride-of-yju/application/dto/create-pride-of-yju.dto.ts
  api/src/pride-of-yju/application/dto/update-pride-of-yju.dto.ts
  api/src/pride-of-yju/application/services/pride-of-yju.service.ts
  api/src/pride-of-yju/domain/entities/pride-of-yju.entity.ts
  api/src/pride-of-yju/domain/repository/pride-of-yju.repository.ts
  api/src/pride-of-yju/infra/entities/pride-of-yju.entity.ts
  api/src/pride-of-yju/infra/mappers/pride-of-yju.mapper.ts
  api/src/pride-of-yju/infra/repository/typeorm-pride-of-yju.repository.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.spec.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.ts
  api/src/pride-of-yju/pride-of-yju.module.ts
  api/test/carousel.e2e-spec.ts
  api/test/jest-e2e.json
  api/test/pride-of-yju.e2e-spec.ts
  api/test/types/carousel-response.ts
  api/test/types/pride-of-yju.response.ts
  files/141735.png
Labels: 💡 Enhancement, 💻 API

#20 post api 제작
  .env
  .github/workflows/main.yml
  api/package-lock.json
  api/package.json
  api/src/common/utils/to-search-target-enum.ts
  api/src/main.ts
  api/src/post/application/service/post.service.spec.ts
  api/src/post/application/service/post.service.ts
  api/src/post/domain/types/searchTarget.ts
  api/src/post/infra/entities/post-orm.entity.ts
  api/src/post/infra/mapper/to-domain.ts
  api/src/post/infra/repository/typeorm-post.repository.spec.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/interface/post.controller.ts
  api/test/post.e2e-spec.ts
  api/test/types/post-response.ts
  docker-compose.yml
Labels: ⭐ Feature

#22 ✅ test : update github action env
  .github/workflows/main.yml
  api/package-lock.json
  api/src/main.ts
Labels: 🐛 BugFix

#24 🔨 CD : make deploy.yml
  .github/workflows/deploy.yml
Labels: 🚀 Deploy

#23 🔨 refactor : 테스트 파일 수정
  api/src/carousel/application/services/carousel.service.spec.ts
  api/src/carousel/application/services/carousel.service.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.spec.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.ts
  api/src/carousel/interface/controllers/carousel.controller.spec.ts
  api/src/carousel/interface/controllers/carousel.controller.ts
  api/test/carousel.e2e-spec.ts
  api/test/types/carousel-response.ts
Labels: ✅ Test, 🛠️ Refactor

#25 도커 파일 제작
  api/Dockerfile
Labels: 🚀 Deploy

#29 ✨ feat : PrideOfYju 모듈 수정, 테스트 코드 수정
  api/src/carousel/application/services/carousel.service.spec.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.spec.ts
  api/src/pride-of-yju/application/services/pride-of-yju.service.spec.ts
  api/src/pride-of-yju/infra/repository/typeorm-pride-of-yju.reposiotry.spec.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.spec.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.ts
  api/test/carousel.e2e-spec.ts
  api/test/pride-of-yju.e2e-spec.ts
  api/test/types/pride-of-yju.response.ts
Labels: ⭐ Feature, 💻 API

#30 staff api 구현 완료, 테스트 코드 제작
  .env
  .github/workflows/main.yml
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/carousel/application/services/carousel.service.spec.ts
  api/src/carousel/interface/controllers/carousel.controller.spec.ts
  api/src/common/types/language.ts
  api/src/common/utils/to-language-enum.ts
  api/src/main.ts
  api/src/post/application/dto/create-post.dto.ts
  api/src/post/application/service/post.service.ts
  api/src/post/domain/entities/post.entity.ts
  api/src/post/domain/repository/post.repository.ts
  api/src/post/infra/entities/post-orm.entity.ts
  api/src/post/infra/repository/typeorm-post.repository.spec.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/interface/post.controller.spec.ts
  api/src/post/interface/post.controller.ts
  api/src/staff/application/dto/create-staff.dto.ts
  api/src/staff/application/service/staff.service.spec.ts
  api/src/staff/application/service/staff.service.ts
  api/src/staff/domain/entities/staff.entity.ts
  api/src/staff/domain/repository/staff.repository.ts
  api/src/staff/infra/entities/staff.entity.ts
  api/src/staff/infra/mappers/staff.mapper.ts
  api/src/staff/infra/repository/typeorm-staff.repository.spec.ts
  api/src/staff/infra/repository/typeorm-staff.repository.ts
  api/src/staff/interface/staff.controller.spec.ts
  api/src/staff/interface/staff.controller.ts
  api/test/carousel.e2e-spec.ts
  api/test/jest-e2e.json
  api/test/post.e2e-spec.ts
  api/test/pride-of-yju.e2e-spec.ts
  api/test/staff.e2e-spec.ts
  api/test/types/staff-response.ts
  docker-compose.yml
Labels: ✅ Test, ⭐ Feature

#35 Refactor/carousel2
  api/src/app.module.ts
  api/src/carousel/application/services/carousel.service.spec.ts
  api/src/carousel/application/services/carousel.service.ts
  api/src/carousel/carousel.module.ts
  api/src/carousel/domain/entities/carousel-return.entiry.ts
  api/src/carousel/domain/entities/carousel.entity.ts
  api/src/carousel/infra/entities/carousel.entity.ts
  api/src/carousel/infra/mappers/carousel.mapper.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.spec.ts
  api/src/carousel/infra/repository/typeorm-carousel.repository.ts
  api/src/carousel/interface/controllers/carousel.controller.spec.ts
  api/src/carousel/interface/controllers/carousel.controller.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.ts
  api/test/__fixtures__/pride/141735.png
  api/test/carousel.e2e-spec.ts
Labels: 🛠️ Refactor, 💻 API

#37 ✅ test : 테스트 코드 수정
  api/src/pride-of-yju/infra/repository/typeorm-pride-of-yju.reposiotry.spec.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.ts
  api/test/carousel.e2e-spec.ts
  api/test/pride-of-yju.e2e-spec.ts
Labels: ✅ Test, 🛠️ Refactor

#38 corporation 구현
  api/src/app.module.ts
  api/src/corporation/application/corporation.service.spec.ts
  api/src/corporation/application/corporation.service.ts
  api/src/corporation/application/dto/create-corporation.dto.ts
  api/src/corporation/application/dto/create-county.dto.ts
  api/src/corporation/application/dto/update-corporation.dto.ts
  api/src/corporation/application/dto/update-country.dto.ts
  api/src/corporation/corporation.module.ts
  api/src/corporation/domain/entities/corporation.entity.ts
  api/src/corporation/domain/entities/country.entity.ts
  api/src/corporation/domain/repository/corporation.repository.ts
  api/src/corporation/infra/entities/corporation.entity.ts
  api/src/corporation/infra/entities/country.entity.ts
  api/src/corporation/infra/mapper/corporation.mapper.ts
  api/src/corporation/infra/repository/typeorm-corporation.repository.spec.ts
  api/src/corporation/infra/repository/typeorm-corporation.repository.ts
  api/src/corporation/interface/corporation.controller.spec.ts
  api/src/corporation/interface/corporation.controller.ts
  api/src/pride-of-yju/infra/repository/typeorm-pride-of-yju.reposiotry.spec.ts
  api/test/corporation.e2e-spec.ts
  api/test/pride-of-yju.e2e-spec.ts
  api/test/types/corporation.response.ts
Labels: ✅ Test, ⭐ Feature

#39 마이그레이션 제작
  api/package.json
  api/src/app.module.ts
  api/src/migrations/1745196878135-CreateTables.ts
  api/src/ormconfig.ts
  api/src/post/infra/entities/post-image-orm.entity.ts
  api/src/post/infra/entities/post-orm.entity.ts
  api/src/post/infra/mapper/to-domain.ts
  api/src/post/infra/repository/typeorm-post.repository.spec.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/test/post.e2e-spec.ts
Labels: 🛠️ Refactor, ⭐ Feature

#40 pride of yju 수정 및 테스트 코드를 더 엄격하게 변경
  api/src/pride-of-yju/application/dto/create-pride-of-yju.dto.ts
  api/src/pride-of-yju/application/services/pride-of-yju.service.spec.ts
  api/src/pride-of-yju/application/services/pride-of-yju.service.ts
  api/src/pride-of-yju/domain/entities/pride-of-yju.entity.ts
  api/src/pride-of-yju/domain/repository/pride-of-yju.repository.ts
  api/src/pride-of-yju/infra/entities/pride-of-yju.entity.ts
  api/src/pride-of-yju/infra/mappers/pride-of-yju.mapper.ts
  api/src/pride-of-yju/infra/repository/typeorm-pride-of-yju.reposiotry.spec.ts
  api/src/pride-of-yju/infra/repository/typeorm-pride-of-yju.repository.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.ts
  api/test/pride-of-yju.e2e-spec.ts
  api/test/types/pride-of-yju.response.ts
Labels: 🛠️ Refactor

#43 Cd/dockerfile
  api/Dockerfile
  api/package-lock.json
  api/package.json
  api/src/jest.setup.ts
  api/src/post/application/service/post.service.ts
  api/test/jest-e2e.json
Labels: ✅ Test, 🐛 BugFix

#47 ✨ feat : /post/main/notices 의 응답에 date 열 추가
  api/src/post/application/service/post.service.spec.ts
  api/src/post/application/service/post.service.ts
  api/src/post/interface/post.controller.spec.ts
  api/src/post/interface/post.controller.ts
  api/test/post.e2e-spec.ts
  api/test/types/post-response.ts
Labels: ⭐ Feature

#48 Feature/authorization
  .env
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/auth/application/dto/login-input.dto.ts
  api/src/auth/application/dto/register-input.dto.ts
  api/src/auth/application/services/token.service.ts
  api/src/auth/application/use-cases/create-user-google.use-case.spec.ts
  api/src/auth/application/use-cases/create-user-google.use-case.ts
  api/src/auth/application/use-cases/create-user.use-case.spec.ts
  api/src/auth/application/use-cases/create-user.use-case.ts
  api/src/auth/application/use-cases/link-google.use-case.ts
  api/src/auth/application/use-cases/login-with-google.use-case.spec.ts
  api/src/auth/application/use-cases/login-with-google.use-case.ts
  api/src/auth/application/use-cases/login.use-case.spec.ts
  api/src/auth/application/use-cases/login.use-case.ts
  api/src/auth/auth.module.ts
  api/src/auth/domain/entities/auth.entity.ts
  api/src/auth/domain/repositories/user-credential.repository.ts
  api/src/auth/domain/services/password.service.ts
  api/src/auth/infra/entities/auth.entity.ts
  api/src/auth/infra/guards/admin.guard.ts
  api/src/auth/infra/guards/auth.guard.ts
  api/src/auth/infra/guards/google-link.guard.ts
  api/src/auth/infra/guards/google.guard.ts
  api/src/auth/infra/guards/jwt-link.guard.ts
  api/src/auth/infra/mappers/auth.mapper.ts
  api/src/auth/infra/repository/typeorm-auth.repository.spec.ts
  api/src/auth/infra/repository/typeorm-auth.repository.ts
  api/src/auth/infra/services/bcrypt-password.service.ts
  api/src/auth/infra/strategy/admin.strategy.ts
  api/src/auth/infra/strategy/google-link.strategy.ts
  api/src/auth/infra/strategy/google.strategy.ts
  api/src/auth/infra/strategy/jwt.strategy.ts
  api/src/auth/infra/types/google.user.ts
  api/src/auth/interface/controller/auth.controller.spec.ts
  api/src/auth/interface/controller/auth.controller.ts
  api/src/common/types/express-index.d.ts
  api/src/main.ts
  api/src/users/application/use-cases/change-user-name-use-case.ts
  api/src/users/application/use-cases/get-all-users.use-case.ts
  api/src/users/application/use-cases/get-user-info.use-case.ts
  api/src/users/domain/entities/user.entity.ts
  api/src/users/domain/repositories/user.repository.ts
  api/src/users/infra/entities/user.entity.ts
  api/src/users/infra/mappers/user.mapper.ts
  api/src/users/infra/repositories/typeorm-user.repository.spec.ts
  api/src/users/infra/repositories/typeorm-user.repository.ts
  api/src/users/interface/controllers/user.controller.spec.ts
  api/src/users/interface/controllers/user.controller.ts
  api/src/users/user.module.ts
  api/test/types/user.response.ts
  api/test/user.e2e-spec.ts
  api/tsconfig.json
  docker-compose.yml
Labels: ✅ Test, ⭐ Feature, 💻 API

#51 📖 docs : .env.example 파일 생성
  .env.example
Labels: 📚 Docs

#52 🔨 refactor : media service 를 media service port 로 변경, post service에서 …
  api/src/carousel/application/services/carousel.service.spec.ts
  api/src/carousel/application/services/carousel.service.ts
  api/src/common/utils/to-search-target-enum.ts
  api/src/media/application/media-service.port.ts
  api/src/media/infra/local-media.service.ts
  api/src/media/media.module.ts
  api/src/post/application/dto/create-post.dto.ts
  api/src/post/application/port/html-parser.port.ts
  api/src/post/application/service/post.service.spec.ts
  api/src/post/application/service/post.service.ts
  api/src/post/domain/repository/post.repository.ts
  api/src/post/domain/types/search-target.enum.ts
  api/src/post/infra/html-parser/jsdom-html-parser-service.spec.ts
  api/src/post/infra/html-parser/jsdom-html-parser-service.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/interface/dto/search-post-query.dto.ts
  api/src/post/interface/post.controller.spec.ts
  api/src/post/interface/post.controller.ts
  api/src/post/post.module.ts
  api/src/pride-of-yju/application/services/pride-of-yju.service.spec.ts
  api/src/pride-of-yju/application/services/pride-of-yju.service.ts
Labels: 🛠️ Refactor
