Repository WhileNotSuccess/project_OIC-Backend_NestJS-deployment-repo, pull requests merged in 2025-05, with the labels that each got.

#57 Refactor/auth
  .github/workflows/main.yml
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/auth/application/dto/change-password.dto.ts
  api/src/auth/application/services/token.service.spec.ts
  api/src/auth/application/use-cases/change-password.use-case.spec.ts
  api/src/auth/application/use-cases/change-password.use-case.ts
  api/src/auth/application/use-cases/create-user-google.use-case.spec.ts
  api/src/auth/application/use-cases/create-user-google.use-case.ts
  api/src/auth/application/use-cases/create-user.use-case.spec.ts
  api/src/auth/application/use-cases/create-user.use-case.ts
  api/src/auth/application/use-cases/link-google.use-case.spec.ts
  api/src/auth/application/use-cases/link-google.use-case.ts
  api/src/auth/application/use-cases/login.use-case.spec.ts
  api/src/auth/auth.module.ts
  api/src/auth/infra/strategy/admin.strategy.spec.ts
  api/src/auth/infra/strategy/admin.strategy.ts
  api/src/auth/infra/strategy/google-link.strategy.spec.ts
  api/src/auth/infra/strategy/google-link.strategy.ts
  api/src/auth/infra/strategy/google.strategy.spec.ts
  api/src/auth/infra/strategy/jwt.strategy.spec.ts
  api/src/auth/infra/strategy/jwt.strategy.ts
  api/src/auth/interface/controller/auth.controller.spec.ts
  api/src/auth/interface/controller/auth.controller.ts
  api/src/common/common.module.ts
  api/src/common/infra/typeorm-transaction-manager.ts
  api/src/common/ports/transaction-manager.port.ts
  api/src/common/types/express-index.d.ts
  api/src/migrations/1745904484149-CreateTables.ts
  api/src/shared/guards/admin.guard.ts
  api/src/shared/guards/auth.guard.ts
  api/src/shared/guards/google-link.guard.ts
  api/src/shared/guards/google.guard.ts
  api/src/shared/guards/jwt-link.guard.ts
  api/src/users/interface/controllers/user.controller.spec.ts
  api/src/users/interface/controllers/user.controller.ts
  api/test/user.e2e-spec.ts
  docker-compose.yml
Labels: ✅ Test, ⭐ Feature, 🐛 BugFix, 💻 API

#58 기존 API에 인증/인가 구현 및 post와 user 연결
  .github/workflows/main.yml
  api/src/auth/infra/repository/typeorm-auth.repository.spec.ts
  api/src/auth/interface/controller/auth.controller.ts
  api/src/carousel/interface/controllers/carousel.controller.ts
  api/src/common/types/custom-request.ts
  api/src/corporation/interface/corporation.controller.ts
  api/src/post/application/dto/post-with-author.dto.ts
  api/src/post/application/query/post-query.repository.ts
  api/src/post/application/service/post.service.spec.ts
  api/src/post/application/service/post.service.ts
  api/src/post/domain/repository/post.repository.ts
  api/src/post/domain/types/search-target.enum.ts
  api/src/post/infra/entities/post-orm.entity.ts
  api/src/post/infra/repository/typeorm-post-query.repository.ts
  api/src/post/infra/repository/typeorm-post.repository.spec.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/interface/post.controller.spec.ts
  api/src/post/interface/post.controller.ts
  api/src/post/post.module.ts
  api/src/pride-of-yju/interface/controllers/pride-of-yju.controller.ts
  api/src/staff/interface/staff.controller.ts
  api/src/users/application/dto/find-all-user.dto.ts
  api/src/users/application/dto/name-change.dto.ts
  api/src/users/application/use-cases/change-user-name-use-case.ts
  api/src/users/infra/entities/user.entity.ts
  api/src/users/infra/repositories/typeorm-user.repository.spec.ts
  api/src/users/interface/controllers/user.controller.spec.ts
  api/src/users/interface/controllers/user.controller.ts
  api/src/users/user.module.ts
  api/test/carousel.e2e-spec.ts
  api/test/corporation.e2e-spec.ts
  api/test/post.e2e-spec.ts
  api/test/pride-of-yju.e2e-spec.ts
  api/test/staff.e2e-spec.ts
  api/test/user.e2e-spec.ts
  docker-compose.yml
Labels: ⭐ Feature

#59 🐛 fix : Fix Swagger error
  api/src/auth/application/dto/change-password.dto.ts
  api/src/auth/application/dto/login-input.dto.ts
  api/src/auth/application/dto/register-input.dto.ts
  api/src/post/application/service/post.service.spec.ts
  api/src/post/application/service/post.service.ts
  api/src/post/domain/types/news.ts
  api/src/post/infra/repository/typeorm-post.repository.spec.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/interface/post.controller.spec.ts
  api/src/post/interface/post.controller.ts
  api/src/users/interface/controllers/user.controller.ts
Labels: 📚 Docs, 🐛 BugFix

#61 🐛 fix : 작성자가 나오도록 수정
  api/src/main.ts
  api/src/migrations/1747632164159-CreateTables.ts
  api/src/post/infra/repository/typeorm-post-query.repository.ts
  api/test/post.e2e-spec.ts
  api/test/types/post-response.ts
  docker-compose.yml
Labels: 🐛 BugFix

#62 🐛 fix : Post 관련 에러 수정 및 swagger 업데이트
  api/src/post/application/dto/post-with-author.dto.ts
  api/src/post/application/dto/post-with-user.dto.ts
  api/src/post/application/query/post-query.repository.ts
  api/src/post/application/service/post.service.spec.ts
  api/src/post/infra/repository/typeorm-post-query.repository.ts
  api/src/post/interface/post.controller.spec.ts
  api/src/post/interface/post.controller.ts
  api/test/post.e2e-spec.ts
Labels: 📚 Docs, 🐛 BugFix

#66 Feature/batch
  api/package-lock.json
  api/package.json
  api/src/app.module.ts
  api/src/batch/application/use-cases/file-cleanup.use-case.spec.ts
  api/src/batch/application/use-cases/file-cleanup.use-case.ts
  api/src/batch/batch.module.ts
  api/src/batch/domain/filesystem/file.service.ts
  api/src/batch/infra/filesystem/file.service.spec.ts
  api/src/batch/infra/filesystem/file.service.ts
  api/src/batch/infra/scheduler/unusedFile.service.ts
  api/src/post/domain/repository/post.repository.ts
  api/src/post/infra/repository/typeorm-post.repository.ts
  api/src/post/post.module.ts
Labels: ⭐ Feature
